//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyRecord
    {
        public long Id { get; set; }
        public Nullable<int> CounterId { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<long> OpeningBalance { get; set; }
        public Nullable<long> ClosingBalance { get; set; }
        public Nullable<long> AccuralAmount { get; set; }
        public Nullable<long> DifferenceAmount { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Counter Counter { get; set; }
    }
}
