//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleteLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CounterId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<long> TransactionDetailId { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Counter Counter { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
        public virtual User User { get; set; }
    }
}
