//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjForms_Localization
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string ControlName { get; set; }
        public string Type { get; set; }
        public string Eng { get; set; }
        public string ZawGyi { get; set; }
        public string MM3 { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public bool AllowToLoad { get; set; }
    
        public virtual pjForm pjForm { get; set; }
    }
}
