//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pjForm
    {
        public pjForm()
        {
            this.pjForms_Localization = new HashSet<pjForms_Localization>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string TextEng { get; set; }
        public string TextMyanmar { get; set; }
        public Nullable<bool> AllowToLoad { get; set; }
    
        public virtual ICollection<pjForms_Localization> pjForms_Localization { get; set; }
    }
}
