//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductPriceChanges = new HashSet<ProductPriceChange>();
            this.TicketButtonAssigns = new HashSet<TicketButtonAssign>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string ProductCode { get; set; }
        public string Barcode { get; set; }
        public long Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string ProductLocation { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductSubCategoryId { get; set; }
        public Nullable<int> MinStockQty { get; set; }
        public decimal DiscountRate { get; set; }
        public Nullable<bool> IsDiscontinue { get; set; }
        public string Size { get; set; }
        public Nullable<bool> IsNotifyMinStock { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<long> WholeSalePrice { get; set; }
        public string UnitType { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        public virtual ICollection<ProductPriceChange> ProductPriceChanges { get; set; }
        public virtual ICollection<TicketButtonAssign> TicketButtonAssigns { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
