//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketButtonAssign
    {
        public int Id { get; set; }
        public string ButtonName { get; set; }
        public string ButtonText { get; set; }
        public Nullable<long> Assignproductid { get; set; }
        public Nullable<int> Defined { get; set; }
        public string Defined1 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
